### PR TITLE
Fix example: return url method from paypal should be GET, not POST

### PR DESCRIPTION
**Pull request by damarev**

### CODE REVIEW

**Comment by fulopattila122** [comment]
This library is heavily work in progress. Please wait a few more days for the first stable version tagged

**Comment by fulopattila122** [comment]
Thx for the PR!

**Comment by damarev** [comment]
@fulopattila122 I have detected another issue with the cancel method, at the PaypalReturnController. Should I open another PR to discuss the issue, or should I wait?

Thank you by the way for the vanilo framework!

**Comment by fulopattila122** [comment]
Please wait. Consider this package as very incomplete at the moment

**Pull request merged**
